import type { AppearanceSettings } from "./appearanceSettings.js";

/** 内置配色：只包含浅深色颜色，与 docs/appearance/presets 同源；套用时只替换 colors。 */
export interface AppearancePalette {
  id: string;
  name: string;
  colors: AppearanceSettings["colors"];
}

export const BUILTIN_APPEARANCE_PALETTES: readonly AppearancePalette[] = [
  {
    id: "builtin-deep-sea",
    name: "深海 · Nord",
    colors: {
      light: {
        background: "#e5e9f0",
        sidebar: "#e5e9f0",
        panel: "#eceff4",
        card: "#ffffff",
        input: "#ffffff",
        brand: "#5e81ac",
        foreground: "#2e3440",
        secondaryText: "#667085",
        border: "#d3d9e3",
        link: "#4c6a92",
        inlineCode: "#d8dee9",
        primary: "#4c6a92",
        primaryText: "#ffffff",
        math: "#8a5a83",
      },
      dark: {
        background: "#242933",
        sidebar: "#242933",
        panel: "#2e3440",
        card: "#3b4252",
        input: "#3b4252",
        brand: "#88c0d0",
        foreground: "#d8dee9",
        secondaryText: "#8f99ad",
        border: "#434c5e",
        link: "#88c0d0",
        inlineCode: "#434c5e",
        primary: "#88c0d0",
        primaryText: "#2e3440",
        math: "#c9a2c2",
      },
    },
  },
  {
    id: "builtin-dusk",
    name: "暮夜 · Tokyo Night",
    colors: {
      light: {
        background: "#e1e2e7",
        sidebar: "#e1e2e7",
        panel: "#eff0f4",
        card: "#ffffff",
        input: "#ffffff",
        brand: "#2e7de9",
        foreground: "#343b58",
        secondaryText: "#6a7091",
        border: "#c9ccd8",
        link: "#1f63c7",
        inlineCode: "#c9ccd8",
        primary: "#1f63c7",
        primaryText: "#ffffff",
        math: "#7847bd",
      },
      dark: {
        background: "#16161e",
        sidebar: "#16161e",
        panel: "#1a1b26",
        card: "#24283b",
        input: "#24283b",
        brand: "#7aa2f7",
        foreground: "#c0caf5",
        secondaryText: "#8189b0",
        border: "#2f3549",
        link: "#7aa2f7",
        inlineCode: "#2f3549",
        primary: "#7aa2f7",
        primaryText: "#16161e",
        math: "#bb9af7",
      },
    },
  },
  {
    id: "builtin-matcha",
    name: "抹茶 · Everforest",
    colors: {
      light: {
        background: "#efebd4",
        sidebar: "#efebd4",
        panel: "#fdf6e3",
        card: "#fffbef",
        input: "#fffbef",
        brand: "#6f8a3a",
        foreground: "#4f5b62",
        secondaryText: "#66716b",
        border: "#ddd8c0",
        link: "#3a7ca5",
        inlineCode: "#ddd8c0",
        primary: "#5f7a2e",
        primaryText: "#ffffff",
        math: "#874a6c",
      },
      dark: {
        background: "#1e2326",
        sidebar: "#1e2326",
        panel: "#272e33",
        card: "#2e383c",
        input: "#2e383c",
        brand: "#a7c080",
        foreground: "#d3c6aa",
        secondaryText: "#9da9a0",
        border: "#414b50",
        link: "#83c092",
        inlineCode: "#414b50",
        primary: "#a7c080",
        primaryText: "#1e2326",
        math: "#d699b6",
      },
    },
  },
  {
    id: "builtin-sand",
    name: "暖砂 · Gruvbox",
    colors: {
      light: {
        background: "#f2e5bc",
        sidebar: "#f2e5bc",
        panel: "#fbf1c7",
        card: "#fffaeb",
        input: "#fffaeb",
        brand: "#af3a03",
        foreground: "#3c3836",
        secondaryText: "#7c6f64",
        border: "#e0cfa9",
        link: "#076678",
        inlineCode: "#e0cfa9",
        primary: "#af3a03",
        primaryText: "#fbf1c7",
        math: "#8f3f71",
      },
      dark: {
        background: "#1d2021",
        sidebar: "#1d2021",
        panel: "#282828",
        card: "#32302f",
        input: "#32302f",
        brand: "#fe8019",
        foreground: "#ebdbb2",
        secondaryText: "#a89984",
        border: "#45403d",
        link: "#83a598",
        inlineCode: "#45403d",
        primary: "#fe8019",
        primaryText: "#1d2021",
        math: "#d3869b",
      },
    },
  },
  {
    id: "builtin-sakura",
    name: "樱雾 · Rosé Pine",
    colors: {
      light: {
        background: "#f2e9e1",
        sidebar: "#f2e9e1",
        panel: "#faf4ed",
        card: "#fffaf3",
        input: "#fffaf3",
        brand: "#d7827e",
        foreground: "#575279",
        secondaryText: "#797593",
        border: "#e4dcd5",
        link: "#286983",
        inlineCode: "#e4dcd5",
        primary: "#b4637a",
        primaryText: "#ffffff",
        math: "#6e5a8f",
      },
      dark: {
        background: "#191724",
        sidebar: "#191724",
        panel: "#1f1d2e",
        card: "#26233a",
        input: "#26233a",
        brand: "#ebbcba",
        foreground: "#e0def4",
        secondaryText: "#908caa",
        border: "#393552",
        link: "#9ccfd8",
        inlineCode: "#393552",
        primary: "#ebbcba",
        primaryText: "#191724",
        math: "#c4a7e7",
      },
    },
  },
  {
    id: "builtin-graphite",
    name: "石墨 · Mono",
    colors: {
      light: {
        background: "#fafafa",
        sidebar: "#f4f4f5",
        panel: "#ffffff",
        card: "#ffffff",
        input: "#ffffff",
        brand: "#2563eb",
        foreground: "#171717",
        secondaryText: "#737373",
        border: "#e5e5e5",
        link: "#2563eb",
        inlineCode: "#e5e5e5",
        primary: "#171717",
        primaryText: "#ffffff",
        math: "#b45309",
      },
      dark: {
        background: "#0a0a0a",
        sidebar: "#0a0a0a",
        panel: "#111111",
        card: "#1a1a1a",
        input: "#1a1a1a",
        brand: "#3b82f6",
        foreground: "#ededed",
        secondaryText: "#8f8f8f",
        border: "#262626",
        link: "#60a5fa",
        inlineCode: "#262626",
        primary: "#ededed",
        primaryText: "#0a0a0a",
        math: "#f5a524",
      },
    },
  },
  {
    id: "builtin-neon",
    name: "霓虹 · Dracula",
    colors: {
      light: {
        background: "#f0eef7",
        sidebar: "#f0eef7",
        panel: "#fbfaff",
        card: "#ffffff",
        input: "#ffffff",
        brand: "#7c3aed",
        foreground: "#282a36",
        secondaryText: "#6b6f85",
        border: "#dcd8ea",
        link: "#0369a1",
        inlineCode: "#dcd8ea",
        primary: "#7c3aed",
        primaryText: "#ffffff",
        math: "#b8327f",
      },
      dark: {
        background: "#1e1f29",
        sidebar: "#1e1f29",
        panel: "#282a36",
        card: "#343746",
        input: "#343746",
        brand: "#bd93f9",
        foreground: "#f8f8f2",
        secondaryText: "#a0a8cc",
        border: "#44475a",
        link: "#8be9fd",
        inlineCode: "#44475a",
        primary: "#bd93f9",
        primaryText: "#1e1f29",
        math: "#ff79c6",
      },
    },
  },
];
